Agencia-Quadreli/Agencia-Quadreli/Models/ErrorViewModel.cs
namespace Agencia_Quadreli.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Agencia-Quadreli/Agencia-Quadreli/Controllers/ContactController.cs
using Microsoft.AspNetCore.Mvc;

namespace Agencia_Quadreli.Controllers {
    public class ContactController : Controller {
        public IActionResult Index() {
            return View();
        }

        
    }
}

Agencia-Quadreli/Agencia-Quadreli/Controllers/HomeController.cs
using System.Diagnostics;
using Agencia_Quadreli.Models;
using Microsoft.AspNetCore.Mvc;

namespace Agencia_Quadreli.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Agencia-Quadreli/Agencia-Quadreli/Controllers/PanelController.cs
using Microsoft.AspNetCore.Mvc;

namespace Agencia_Quadreli.Controllers
{
    public class PanelController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult CarregarSessao(String nomeDaSecao)
        {
            switch (nomeDaSecao)
            {
                case "Dashboard":
                    return PartialView("_Dashboard");

                case "Textos":
                    return PartialView("_Textos");

                case "Imagens":
                    return PartialView("_Imagens");

                case "Servicos":
                    return PartialView("_Servicos");

                case "Depoimentos":
                    return PartialView("_Depoimentos");
                
                case "Portifolio":
                    return PartialView("_Portifolio");

                case "Contato":
                    return PartialView("_Contato");

                case "Seo":
                    return PartialView("_Seo");
                
                case "Geral":
                    return PartialView("_Geral");

                case "Usuarios":
                    return PartialView("_Usuarios");

                default:
                    return NotFound();
            }
            
        }
    }
}

Agencia-Quadreli/Agencia-Quadreli/Controllers/PortfolioController.cs
using Microsoft.AspNetCore.Mvc;

namespace Agencia_Quadreli.Controllers {
    public class PortfolioController : Controller {
        public IActionResult Index() {
            return View();
        }
    }
}

Agencia-Quadreli/Agencia-Quadreli/Views/Contact/Index.cshtml
@{
    ViewData["Title"] = "Contato";
}

<head>
    <link href="~/css/contact.css" rel="stylesheet" />
</head>

<section class="form-sec">
    <div class="container flex">
        <div class="form-wrapper flex">
            <h1>Orçamento por email</h1>
            <form action="/" method="post">
                <div class="form-line flex">
                    <label for="name">Nome:</label>
                    <input type="text" name="name" placeholder="Digite seu Nome..."/>
                </div><!--form-line-->

                <div class="form-line flex">
                    <label for="phone">Celular:</label>
                    <input type="text" name="phone" placeholder="Digite o seu numero de whatsapp..."/>
                </div><!--form-line-->

                <div class="form-line flex">
                    <label for="message">Mensagem:</label>
                    <textarea name="message" placeholder="Digite a sua mensagem..."></textarea>
                </div><!--form-line-->

                <button type="submit">Enviar</button>
            </form>
        </div><!--form-wrapper-->
        <div class="zap-wrapper flex">
            <div class="zap-icon"></div>
            <div class="zap-texto">
                <p>Faça o orçamento por whatsapp</p>
                <a href="https://api.whatsapp.com/send/?phone=5517981336263&text&type=phone_number&app_absent=0">Clique aqui</a>
            </div>
        </div><!--zap-wrapper-->
    </div><!--container-->
</section>

Agencia-Quadreli/Agencia-Quadreli/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Início";
}

<!--NENHUMA IMAGEM SERA OFICIAL AINDA-->

<head>
    <link href="~/css/home.css" rel="stylesheet" />
</head>

<section class="first-sec">
    <div class="container">
        <!--procurar imagem para lado direito e depois colocar o texto do lado diteiro-->
        <div class="texto-header">
            <h1>Agência Quadreli</h1>
            <h3>Design estratégico que comunica e conecta</h3>
        </div><!--texto-header-->
        <div class="imagem-header">
            <div class="overlay"></div>
            <img src="~/img/banners/Image01.png" alt="Alternate Text" />
        </div><!--imagem-header-->
    </div><!--container-->
</section><!--first-sec-->

<section class="HOME-about">
    <div class="container">
        <div class="envolto flex">
            <h4>Da Identidade Visual ao Digital, unimos criatividade e estratégia para gerar resultados</h4>
            <div class="texto">
                <p>
                    Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed non odio fringilla, interdum mauris vitae, consectetur nibh. Phasellus laoreet blandit sem. Aenean convallis quam vitae eleifend venenatis. Phasellus aliquet posuere dui, et mollis sapien tempor vitae. Quisque elementum blandit nisl, congue varius metus sollicitudin nec. Nunc sit amet lacus ut magna fringilla scelerisque. Etiam pretium augue a scelerisque ullamcorper. Nullam pulvinar sit amet turpis id rutrum. Etiam nisl tellus, pellentesque ac commodo mollis, sodales semper libero. Suspendisse eu magna arcu. Integer efficitur lorem a massa feugiat, in elementum turpis vulputate. In hac habitasse platea dictumst.
                </p>

                <div class="link-wrapper flex">
                    <a class="link" asp-controller="Contact" asp-action="Index">Faça um orçamento</a>
                </div><!--link-wrapper-->
            </div><!--texto-->

            <div class="imagem">
                <div class="img"></div><!--substituir por img depois-->
            </div><!--imagem-->
                
        </div><!--flex-->
    </div><!--container-->
</section><!--HOME-bem-vindo-->

<section class="HOME-servicos">
    <div class="container">
        <h1 class="titulo">Nossos Serviços</h1>
        <div class="servicos-wrapper flex">
            <div class="texto-servicos">
                <p>Posicione sua marca nos canais onde as pessoas buscam informação diariamente.</p>
                <p>Investir em Marketing Digital ajuda você a promover seus produtos ou serviços em várias plataformas no ambiente digital, incluindo uso de canais como Redes Sociais</p>
                <p>
                    Seu diferencial é a capacidade de mensurar resultados em tempo real. Isso ajuda a economizar e personalizar suas ações
                </p>
            </div>
            
            <div id="qua1" class="quadro-servico"></div><!--quadro-servicos-->
            <div id="qua2" class="quadro-servico"></div><!--quadro-servicos-->
            <div id="qua3" class="quadro-servico"></div><!--quadro-servicos-->
            <div class="icons-wrapper flex">
                <div style="background-image:url(/img/icons/EUAflag.png);" class="icon"></div>
                <div style="background-image:url(/img/icons/BRflag.png);" class="icon"></div>
                <div style="background-image:url(/img/icons/PTflag.png);" class="icon"></div>
            </div><!--icons-wrapper-->
        </div><!--servicos-wrapper-->
        
    </div><!--container-->
</section><!--HOME-servicos-->

<section class="HOME-portfolio">
    <div class="container">
        <h1 class="titulo">Nossos Projetos</h1>
        <div class="mosaico grid">
            <div class="image">
                <div class="overlay overlay-image">
                    <div class="overlay-info flex">
                        <p id="MarcaNome">Marca</p>
                        <p id="MarcaCategoria">Categoria e algo mais</p>
                        <a asp-controller="Portfolio" asp-action="Index">Ver Mais</a>
                    </div><!--overlay-info-->
                </div><!--overlay-image-->
                <img src="~/img/portifolio/TB Campanha maes.png" />
            </div><!--image-->
            <div class="image">
                <div class="overlay overlay-image">
                    <div class="overlay-info flex">
                        <p id="MarcaNome">Marca</p>
                        <p id="MarcaCategoria">Categoria e algo mais</p>
                        <a asp-controller="Portfolio" asp-action="Index">Ver Mais</a>
                    </div><!--overlay-info-->
                </div><!--overlay-image-->
                <img src="~/img/portifolio/BOTAFOGO X NH 1.png" alt="Alternate Text" />
            </div><!--image-->
            <div class="image">
                <div class="overlay overlay-image">
                    <div class="overlay-info flex">
                        <p id="MarcaNome">Marca</p>
                        <p id="MarcaCategoria">Categoria e algo mais</p>
                        <a asp-controller="Portfolio" asp-action="Index">Ver Mais</a>
                    </div><!--overlay-info-->
                </div><!--overlay-image-->
                <img src="~/img/portifolio/dia do cliente2024.png" alt="Alternate Text" />
            </div><!--image-->
            <div class="image">
                <div class="overlay overlay-image">
                    <div class="overlay-info flex">
                        <p id="MarcaNome">Marca</p>
                        <p id="MarcaCategoria">Categoria e algo mais</p>
                        <a asp-controller="Portfolio" asp-action="Index">Ver Mais</a>
                    </div><!--overlay-info-->
                </div><!--overlay-image-->
                <img src="~/img/portifolio/TB Campanha maes.png" />
            </div><!--image-->
            <div class="image">
                <div class="overlay overlay-image">
                    <div class="overlay-info flex">
                        <p id="MarcaNome">Marca</p>
                        <p id="MarcaCategoria">Categoria e algo mais</p>
                        <a asp-controller="Portfolio" asp-action="Index">Ver Mais</a>
                    </div><!--overlay-info-->
                </div><!--overlay-image-->
                <img src="~/img/portifolio/BOTAFOGO X NH 1.png" alt="Alternate Text" />
            </div><!--image-->
            <div class="image">
                <div class="overlay overlay-image">
                    <div class="overlay-info flex">
                        <p id="MarcaNome">Marca</p>
                        <p id="MarcaCategoria">Categoria e algo mais</p>
                        <a asp-controller="Portfolio" asp-action="Index">Ver Mais</a>
                    </div><!--overlay-info-->
                </div><!--overlay-image-->
                <img src="~/img/portifolio/dia do cliente2024.png" alt="Alternate Text" />
            </div><!--image-->
        </div><!--mosaico-->

        <div class="link-wrapper flex">
            <a class="link" asp-controller="Contact" asp-action="Index">Faça um orçamento</a>
        </div><!--link-wrapper-->

    </div><!--container-->
</section><!--HOME-portifolio-->

<section class="HOME-depoimentos">
    <div class="container">
        <div class="depoimentos-wrapper">
            <img class="aspas aspas-abre" src="~/img/Outros/aspas abre.png" />
            <div class="depoimento-slide active">
                <div class="profile-info">
                    <img />
                    <span>- Ana Carvalho</span>
                </div><!--profile-->
                <p>"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam ut nunc diam. Vestibulum ante ipsum primis in faucibus orci luctus et"</p>
            </div>
            <div class="depoimento-slide">
                <p>"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam ut nunc diam. Vestibulum ante ipsum primis in faucibus orci luctus et"</p>
            </div>
            <div class="depoimento-slide">
                <p>"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam ut nunc diam. Vestibulum ante ipsum primis in faucibus orci luctus et"</p>
            </div>
            <img class="aspas aspas-fecha" src="~/img/Outros/aspas fecha.png"/>
        </div><!--depoimentos-wrapper-->
        <div class="dots-wrapper flex">
            <div class="dot active"></div>
            <div class="dot"></div>
            <div class="dot"></div> 
        </div><!--dots-wrapper-->
    </div><!--container-->
</section><!--HOME-depoimentos-->

Agencia-Quadreli/Agencia-Quadreli/Views/Panel/Index.cshtml
@{
    ViewData["Title"] = "Painel de Controle";
    ViewData["SemMenuFooter"] = true;
}

@section Styles{
    <link href="~/css/panel.css" rel="stylesheet" />
}

@section Scripts {
    <script src="~/js/panel.js" asp-append-version="true"></script>
}

<section class="Panel">
    <div class="container">
        <nav class="sidebar">
            <ul>
                <li><a class="ajax-link" href="/Panel/Dashboard">Inicio</a></li>
                 
                <li>
                    <span id="conteudos">Conteudos <i class="seta fa-solid fa-chevron-down"></i></span>
                    <ul class="conteudos">
                        <li><a class="ajax-link" href="/Panel/Textos">Textos</a></li>
                        <li><a class="ajax-link" href="/Panel/Imagens">Imagens</a></li>
                        <li><a class="ajax-link" href="/Panel/Servicos">Servicos</a></li>
                        <li><a class="ajax-link" href="/Panel/Depoimentos">Depoimentos</a></li>
                        <li><a class="ajax-link" href="/Panel/Portifolio">Portifolio</a></li>
                    </ul>
                </li>

                <li>
                    <span id="configuracoes">Configuracoes <i class="seta fa-solid fa-chevron-down"></i></span>
                    <ul class="configuracoes">
                        <li><a class="ajax-link" href="/Panel/Contato">Contato</a></li>
                        <li><a class="ajax-link" href="/Panel/Seo">SEO</a></li>
                        <li><a class="ajax-link" href="/Panel/Geral">Geral</a></li>
                    </ul>
                </li>

                <li><a class="ajax-link" href="/Panel/Usuarios">Usuarios</a></li>
            </ul>
        </nav><!--menu-->
        <div class="conteudo-panel">
            <div class="main-wrapper" id="conteudo-dinamico">
                
            </div><!--main-wrapper-->
        </div><!--conteudo-panel-->
    </div><!--container-->
</section>

Agencia-Quadreli/Agencia-Quadreli/Views/Panel/_Contato.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

Agencia-Quadreli/Agencia-Quadreli/Views/Panel/_Dashboard.cshtml
<h4>Ínicio</h4>
<div class="line"></div>

<div class="envolto-panel">
    <div class="wrapper access-report">
        <p>Total de acessos:</p>
    </div><!--access-report-->

    <div class="wrapper clicks-quote">
        <p>Cliques em "Fazer orcamento"</p>
    </div><!--clicks-quote-->
</div>

Agencia-Quadreli/Agencia-Quadreli/Views/Panel/_Depoimentos.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

Agencia-Quadreli/Agencia-Quadreli/Views/Panel/_Geral.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

Agencia-Quadreli/Agencia-Quadreli/Views/Panel/_Imagens.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

Agencia-Quadreli/Agencia-Quadreli/Views/Panel/_Portifolio.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

Agencia-Quadreli/Agencia-Quadreli/Views/Panel/_Seo.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

Agencia-Quadreli/Agencia-Quadreli/Views/Panel/_Servicos.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

Agencia-Quadreli/Agencia-Quadreli/Views/Panel/_Textos.cshtml
<h4>Textos</h4>
<div class="line"></div>

Agencia-Quadreli/Agencia-Quadreli/Views/Panel/_Usuarios.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

Agencia-Quadreli/Agencia-Quadreli/Views/Portfolio/Index.cshtml
@{
    ViewData["Title"] = "Portifólio";
}

<head>
    <link href="~/css/portfolio.css" rel="stylesheet" />
</head>

<section>
    <div class="container">
        <h1>Portfólio</h1>
            <nav class="select-bar">
                <a class="selected" href="#">Todos</a>
                <a href="#">Redes Sociais</a>
                <a href="#">Design Gráfico</a>
            </nav><!--select-bar-->
        <div class="selection-wrapper">
            <div class="selected-image">
                <img src="~/img/portifolio/8 marco.png" alt="Alternate Text" />
            </div>
            <div class="selected-image">
                <img src="~/img/portifolio/8 marco.png" alt="Alternate Text" />
            </div>
            <div class="selected-image">
                <img src="~/img/portifolio/8 marco.png" alt="Alternate Text" />
            </div>
            <div class="selected-image">
                <img src="~/img/portifolio/8 marco.png" alt="Alternate Text" />
            </div>
            <div class="selected-image">
                <img src="~/img/portifolio/8 marco.png" alt="Alternate Text" />
            </div>
            <div class="selected-image">
                <img src="~/img/portifolio/8 marco.png" alt="Alternate Text" />
            </div>
        </div><!--selections-wrapper-->
    </div><!--container-->
</section>

Agencia-Quadreli/Agencia-Quadreli/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <title>@ViewData["Title"] - Agencia Quadreli</title>
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
        <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
        <link rel="stylesheet" href="//use.fontawesome.com/releases/v6.7.0/css/all.css">
        @await RenderSectionAsync("Styles", required: false)
    </head>
    <body>
        @if (!(ViewData["SemMenuFooter"] as bool? ?? false)){
            
            <header>
                <nav class="menu-cima fixed-top">
                    <div class="container">
                        <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">
                            <div class="logo-header"><img src="~/img/logo/WhiteLogo.png"/></div><!--substituir por <img> depois>-->
                        </a>
                        <div class="menu-link">
                            <a class="menu-opt" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                            <a class="menu-opt" asp-area="" asp-controller="Portfolio" asp-action="Index">Portifolio</a>
                            <a class="menu-opt" asp-area="" asp-controller="Contact" asp-action="Index">Contato</a>
                        </div><!--menu-link-->
                    </div><!--container-->
                </nav><!--Menu-cima-->
            </header>

        }

        <div class="container fora">
            <main role="main">
                @RenderBody()
            </main>
        </div>

        @if (!(ViewData["SemMenuFooter"] as bool? ?? false)){

            <footer class="footer text-muted">
                <div class="container rodape">
                    <div class="logo-footer"><img src="~/img/logo/WhiteLogo.png" /></div>
                    <p>&copy; 2025 - Agencia Quadreli</p>
                </div><!--rodape-->
            </footer>
        }

        <script src="~/lib/jquery/dist/jquery.min.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>

        @if (!(ViewData["SemMenuFooter"] as bool? ?? false)){
        <script src="~/js/site.js" asp-append-version="true"></script>
        }

        @await RenderSectionAsync("Scripts", required: false)
    </body>
</html>